apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: pickelball-app
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: "ZGZ2eHVhaWJm"
  CLOUDINARY_API_KEY: "NjgyNjI3NTEzODc5Njgx"
  CLOUDINARY_API_SECRET: "Qkp6NzItSVZCeHl0OXhYRkdUVURUNTdGUksw"
  JWT_SECRET_KEY: "NGI3NGJjMjAxZGRmYzAzNmRiM2YyY2Y4MTcxNTY1YTMwNmRmZmE3Y2FlZjUwNzRlYTk0MjlkZGY3NTMyNTIyNzIyZThhMzZmNjk5OTQ1ZDM0ZTYwNWIzNGY5YTMzZDg5ZjAwMDg0MTk3ZTM1NjRhOGJhNmE5NDhlNmMyYWQxY2U="
  STRIPE_SECRET_KEY: "c2tfdGVzdF81MVJ5YzdoQmxMb0c0SldlZjNqcmpXS24yd3FzaTJhb0FjTzZlZFVYaWNEVWFjV3RkWmVJSEVNak1DeTZwSllIZHFveHdMakJZMVAwRDhCcUM2RXJhN3NxYzAwemhZeFptdnE="
